import type { Metadata } from "next";
import "../Style/Normalize.css";
import "../Style/Root.css";
import "../Style/Style.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Small Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
